-- Supabase RLS policies for Nasab Al-Baraja
-- Admin management is now data-driven through public.admin_users.
-- Seeded initial admin:
--   dillahbaraja@gmail.com
--
-- Before running:
-- 1. Authentication > Providers > Anonymous = enabled
-- 2. Your service-role key is stored only outside the repo

create table if not exists public.admin_users (
  id bigint generated by default as identity primary key,
  email text not null unique,
  created_at timestamptz not null default now()
);

alter table public.admin_users enable row level security;
alter table public.nodes enable row level security;
alter table public.notices enable row level security;

grant usage on schema public to anon, authenticated;
grant select on public.admin_users to authenticated;
grant select, insert, update, delete on public.nodes to anon, authenticated;
grant select, insert, update, delete on public.notices to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

create or replace function public.is_admin_user()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.admin_users
    where email = auth.jwt() ->> 'email'
  );
$$;

insert into public.admin_users (email)
values ('dillahbaraja@gmail.com')
on conflict (email) do nothing;

-- Clear old policies
drop policy if exists "admin_users_select_self" on public.admin_users;
drop policy if exists "admin_users_admin_full_access" on public.admin_users;

drop policy if exists "nodes_read_all" on public.nodes;
drop policy if exists "nodes_insert_pending_public" on public.nodes;
drop policy if exists "nodes_update_pending_public" on public.nodes;
drop policy if exists "nodes_update_name_change_public" on public.nodes;
drop policy if exists "nodes_delete_pending_public" on public.nodes;
drop policy if exists "nodes_admin_full_access" on public.nodes;

drop policy if exists "notices_read_all" on public.notices;
drop policy if exists "notices_insert_public_proposals" on public.notices;
drop policy if exists "notices_admin_full_access" on public.notices;

create policy "admin_users_select_self"
on public.admin_users
for select
to authenticated
using (email = auth.jwt() ->> 'email');

create policy "admin_users_admin_full_access"
on public.admin_users
for all
to authenticated
using (public.is_admin_user())
with check (public.is_admin_user());

-- Public read
create policy "nodes_read_all"
on public.nodes
for select
to anon, authenticated
using (true);

create policy "notices_read_all"
on public.notices
for select
to anon, authenticated
using (true);

-- Public can create pending child suggestions only
create policy "nodes_insert_pending_public"
on public.nodes
for insert
to anon, authenticated
with check (
  coalesce(moderation->>'status', '') = 'pending'
  and coalesce(moderation->>'type', '') = 'add_child'
);

-- Public can update rows that are already pending
create policy "nodes_update_pending_public"
on public.nodes
for update
to anon, authenticated
using (
  coalesce(moderation->>'status', '') = 'pending'
)
with check (
  coalesce(moderation->>'status', '') = 'pending'
  and (
    coalesce(moderation->>'type', '') = 'add_child'
    or moderation ? 'nameChange'
  )
);

-- Public can add/edit pending name change on a normal node
create policy "nodes_update_name_change_public"
on public.nodes
for update
to anon, authenticated
using (true)
with check (
  moderation ? 'nameChange'
  and coalesce(moderation->'nameChange'->>'status', '') = 'pending'
);

-- Public can cancel/delete only pending suggestion rows
create policy "nodes_delete_pending_public"
on public.nodes
for delete
to anon, authenticated
using (
  coalesce(moderation->>'status', '') = 'pending'
);

-- Admin full access to nodes
create policy "nodes_admin_full_access"
on public.nodes
for all
to authenticated
using (public.is_admin_user())
with check (public.is_admin_user());

-- Public can create proposal notices
create policy "notices_insert_public_proposals"
on public.notices
for insert
to anon, authenticated
with check (
  type in ('proposal_add_child', 'proposal_name_change')
);

-- Admin full access to notices
create policy "notices_admin_full_access"
on public.notices
for all
to authenticated
using (public.is_admin_user())
with check (public.is_admin_user());
