-- Supabase RLS policies for Nasab Al-Baraja
-- Admin management is now data-driven through public.admin_users.
-- Seeded initial admin:
--   dillahbaraja@gmail.com
--
-- Before running:
-- 1. Authentication > Providers > Anonymous = enabled
-- 2. Your service-role key is stored only outside the repo

create table if not exists public.admin_users (
  id bigint generated by default as identity primary key,
  email text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.baraja_member (
  id bigint generated by default as identity primary key,
  auth_user_id uuid not null unique,
  person_id text not null,
  email text not null unique,
  phone text not null default '',
  city text not null default '',
  country text not null default '',
  claim_status text not null default 'pending',
  member_level text not null default 'guest',
  arabic_name_snapshot text not null default '',
  english_name_snapshot text not null default '',
  approved_at timestamptz,
  approved_by_member_id bigint references public.baraja_member(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint baraja_member_claim_status_check check (claim_status in ('pending', 'approved', 'rejected', 'cancelled')),
  constraint baraja_member_level_check check (member_level in ('guest', 'verified', 'admin'))
);

alter table public.admin_users enable row level security;
alter table public.baraja_member enable row level security;
alter table public.nodes enable row level security;
alter table public.notices enable row level security;

drop view if exists public.baraja_member_public_status;

alter table public.baraja_member
alter column person_id type text
using person_id::text;

alter table public.baraja_member
add column if not exists country text not null default '';

grant usage on schema public to anon, authenticated;
grant select on public.admin_users to authenticated;
grant select, insert, update, delete on public.baraja_member to authenticated;
grant select, insert, update, delete on public.nodes to anon, authenticated;
grant select, insert, update, delete on public.notices to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

create or replace function public.is_admin_user()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.admin_users
    where email = auth.jwt() ->> 'email'
  )
  or exists (
    select 1
    from public.baraja_member
    where auth_user_id = auth.uid()
      and claim_status = 'approved'
      and member_level = 'admin'
  );
$$;

create or replace function public.current_baraja_member_id()
returns bigint
language sql
stable
security definer
set search_path = public
as $$
  select id
  from public.baraja_member
  where auth_user_id = auth.uid()
  order by id asc
  limit 1;
$$;

create or replace function public.is_verified_baraja_member()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.baraja_member
    where auth_user_id = auth.uid()
      and claim_status = 'approved'
      and member_level in ('verified', 'admin')
  );
$$;

create or replace function public.is_admin_baraja_member()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.baraja_member
    where auth_user_id = auth.uid()
      and claim_status = 'approved'
      and member_level = 'admin'
  );
$$;

create or replace function public.can_manage_baraja_members()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.is_verified_baraja_member() or public.is_admin_baraja_member() or public.is_admin_user();
$$;

create or replace function public.touch_baraja_member_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.enforce_baraja_member_update_guard()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() = old.auth_user_id and not public.can_manage_baraja_members() then
    if new.person_id <> old.person_id
      or new.auth_user_id <> old.auth_user_id
      or new.claim_status <> old.claim_status
      or new.member_level <> old.member_level
      or coalesce(new.approved_by_member_id, -1) <> coalesce(old.approved_by_member_id, -1)
      or coalesce(new.approved_at, timestamptz 'epoch') <> coalesce(old.approved_at, timestamptz 'epoch')
      or new.arabic_name_snapshot <> old.arabic_name_snapshot
      or new.english_name_snapshot <> old.english_name_snapshot
      or new.email <> old.email then
      raise exception 'You can only update your own profile fields.';
    end if;
  end if;

  return new;
end;
$$;

drop trigger if exists baraja_member_touch_updated_at on public.baraja_member;
create trigger baraja_member_touch_updated_at
before update on public.baraja_member
for each row
execute function public.touch_baraja_member_updated_at();

drop trigger if exists baraja_member_update_guard on public.baraja_member;
create trigger baraja_member_update_guard
before update on public.baraja_member
for each row
execute function public.enforce_baraja_member_update_guard();

create unique index if not exists baraja_member_one_approved_per_person_idx
on public.baraja_member (person_id)
where claim_status = 'approved';

create unique index if not exists baraja_member_one_pending_per_person_idx
on public.baraja_member (person_id)
where claim_status = 'pending';

create or replace view public.baraja_member_public_status as
select
  person_id,
  case
    when bool_or(claim_status = 'approved') then 'approved'
    when bool_or(claim_status = 'pending') then 'pending'
    else 'none'
  end as claim_status
from public.baraja_member
where claim_status in ('pending', 'approved')
group by person_id;

grant select on public.baraja_member_public_status to anon, authenticated;

create or replace function public.approve_baraja_member_claim(target_member_id bigint)
returns public.baraja_member
language plpgsql
security definer
set search_path = public
as $$
declare
  target_row public.baraja_member;
  approver_id bigint;
begin
  if not public.can_manage_baraja_members() then
    raise exception 'Only verified members or admins can approve claims.';
  end if;

  approver_id := public.current_baraja_member_id();

  select *
  into target_row
  from public.baraja_member
  where id = target_member_id
  for update;

  if not found then
    raise exception 'Target member claim was not found.';
  end if;

  if target_row.claim_status <> 'pending' then
    raise exception 'Only pending claims can be approved.';
  end if;

  if exists (
    select 1
    from public.baraja_member
    where person_id = target_row.person_id
      and claim_status = 'approved'
      and id <> target_member_id
  ) then
    raise exception 'This person is already connected to another approved member.';
  end if;

  update public.baraja_member
  set
    claim_status = 'approved',
    member_level = case when member_level = 'admin' then 'admin' else 'verified' end,
    approved_at = now(),
    approved_by_member_id = approver_id
  where id = target_member_id
  returning * into target_row;

  return target_row;
end;
$$;

create or replace function public.promote_baraja_member_admin(target_member_id bigint)
returns public.baraja_member
language plpgsql
security definer
set search_path = public
as $$
declare
  target_row public.baraja_member;
begin
  if not public.is_admin_baraja_member() then
    raise exception 'Only admins can promote another member.';
  end if;

  update public.baraja_member
  set member_level = 'admin'
  where id = target_member_id
    and claim_status = 'approved'
    and member_level in ('verified', 'admin')
  returning * into target_row;

  if not found then
    raise exception 'Target member must be an approved verified member.';
  end if;

  return target_row;
end;
$$;

insert into public.admin_users (email)
values ('dillahbaraja@gmail.com')
on conflict (email) do nothing;

-- Clear old policies
drop policy if exists "admin_users_select_self" on public.admin_users;
drop policy if exists "admin_users_admin_full_access" on public.admin_users;
drop policy if exists "baraja_member_select_self_or_manager" on public.baraja_member;
drop policy if exists "baraja_member_insert_own_claim" on public.baraja_member;
drop policy if exists "baraja_member_update_self" on public.baraja_member;
drop policy if exists "baraja_member_delete_manager_pending" on public.baraja_member;

drop policy if exists "nodes_read_all" on public.nodes;
drop policy if exists "nodes_insert_pending_public" on public.nodes;
drop policy if exists "nodes_update_pending_public" on public.nodes;
drop policy if exists "nodes_update_name_change_public" on public.nodes;
drop policy if exists "nodes_delete_pending_public" on public.nodes;
drop policy if exists "nodes_admin_full_access" on public.nodes;

drop policy if exists "notices_read_all" on public.notices;
drop policy if exists "notices_insert_public_proposals" on public.notices;
drop policy if exists "notices_admin_full_access" on public.notices;

create policy "admin_users_select_self"
on public.admin_users
for select
to authenticated
using (email = auth.jwt() ->> 'email');

create policy "admin_users_admin_full_access"
on public.admin_users
for all
to authenticated
using (public.is_admin_user())
with check (public.is_admin_user());

create policy "baraja_member_select_self_or_manager"
on public.baraja_member
for select
to authenticated
using (
  auth.uid() = auth_user_id
  or public.can_manage_baraja_members()
);

create policy "baraja_member_insert_own_claim"
on public.baraja_member
for insert
to authenticated
with check (
  auth.uid() = auth_user_id
  and claim_status = 'pending'
  and member_level = 'guest'
);

create policy "baraja_member_update_self"
on public.baraja_member
for update
to authenticated
using (
  auth.uid() = auth_user_id
)
with check (
  auth.uid() = auth_user_id
);

create policy "baraja_member_delete_manager_pending"
on public.baraja_member
for delete
to authenticated
using (
  public.can_manage_baraja_members()
  and claim_status = 'pending'
);

-- Public read
create policy "nodes_read_all"
on public.nodes
for select
to anon, authenticated
using (true);

create policy "notices_read_all"
on public.notices
for select
to anon, authenticated
using (true);

-- Public can create pending child suggestions only
create policy "nodes_insert_pending_public"
on public.nodes
for insert
to anon, authenticated
with check (
  coalesce(moderation->>'status', '') = 'pending'
  and coalesce(moderation->>'type', '') = 'add_child'
);

-- Public can update rows that are already pending
create policy "nodes_update_pending_public"
on public.nodes
for update
to anon, authenticated
using (
  coalesce(moderation->>'status', '') = 'pending'
)
with check (
  coalesce(moderation->>'status', '') = 'pending'
  and (
    coalesce(moderation->>'type', '') = 'add_child'
    or moderation ? 'nameChange'
  )
);

-- Public can add/edit pending name change on a normal node
create policy "nodes_update_name_change_public"
on public.nodes
for update
to anon, authenticated
using (true)
with check (
  moderation ? 'nameChange'
  and coalesce(moderation->'nameChange'->>'status', '') = 'pending'
);

-- Public can cancel/delete only pending suggestion rows
create policy "nodes_delete_pending_public"
on public.nodes
for delete
to anon, authenticated
using (
  coalesce(moderation->>'status', '') = 'pending'
);

-- Admin full access to nodes
create policy "nodes_admin_full_access"
on public.nodes
for all
to authenticated
using (public.is_admin_user())
with check (public.is_admin_user());

-- Public can create proposal notices
create policy "notices_insert_public_proposals"
on public.notices
for insert
to anon, authenticated
with check (
  type in ('proposal_add_child', 'proposal_name_change')
);

-- Admin full access to notices
create policy "notices_admin_full_access"
on public.notices
for all
to authenticated
using (public.is_admin_user())
with check (public.is_admin_user());
